### PR TITLE
chore(deps): upgrade all deps

### LINKED ISSUE #307: Dependencies are old
We're still using webpack v4, older versions of Patternfly and React, etc. These should all be upgraded.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #307

### CODE REVIEW

**Comment by jan-law** [comment]
I noticed the text font looks slightly different. There's a warning in the console:
image

**Comment by andrewazores** [comment]
Hmm. The right side image on the About modal is also missing now.

**Comment by andrewazores** [comment]
Fonts and About modal image seem to work the same as before the PR now.

**Review by jan-law — APPROVED** [review]
Looks good!

**Pull request merged**
