### PR TITLE
build(deps): upgrade to Patternfly 5

### LINKED ISSUE #1110: [Epic] Upgrade to Patternfly v5
### Describe the feature

Patternfly v5 is out: https://www.patternfly.org/

Cryostat Web is currently using v4: http://v4-archive.patternfly.org/v4/

Upgrade doc: https://www.patternfly.org/get-started/upgrade/

### Anything other information?

_No response_

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #1110 

## Description of the change:

WIP

## Motivation for the change:

WIP

### CODE REVIEW

**Comment by andrewazores** [comment]
@tthvo just a heads up - this repo got forked into https://github.com/cryostatio/cryostat-web-2.x .

This one is the active development one which is linked to the cryostat3 backend.

The new fork is cut from a recent commit, and is the one that will continue on (for a short while) for any working targeting 2.4.x that may come.

This PR is OK to just stay here in this repo, there is no need to backport this to the 2.x fork once it's ready.

**Comment by tthvo** [comment]
Ahh thanks for the heads up! I will keep that in mind!

**Comment by tthvo** [comment]
Closing this as it is way overdue and potentially merge conflicts. Hey @andrewazores, let's create an upstream `pf5` branch like `cryostat3` and migrate one by one there?

This PR can serve as a reference to port whichever usable later to upstream branch.

**Comment by andrewazores** [comment]
Yup, I'll be creating upstream release branches (`cryostat-v3.0`) today or tomorrow, and after that I will create `pf5` off of `main`.

**Comment by tthvo** [comment]
Sounds good! Thanks!

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-web/tree/pf5

**Comment by andrewazores** [comment]
Merge conflicts are probably just text updates from #1260

**Comment by andrewazores** [comment]
@tthvo if you can resolve these merge conflicts, we can get this merged into the upstream feature branch so that the work can continue there. Once that branch diverges from `main` we can create a draft PR to track its progress and also keep it up to date with `main` more easily.

**Comment by tthvo** [comment]
okay, sounds good! I will have a look at the end of this week!

**Comment by tthvo** [comment]
Merge conflicts are resolved now. Lots of things and tests are still broken but building web assets with webpack is good (i.e. `yarn build:notests` and `yarn start:dev` should all work).

**Comment by andrewazores** [comment]
Merging this into the upstream feature branch now.

**Pull request merged**
