### PR TITLE
build(config): add build properties JSON file

### LINKED ISSUE #548: [Task] Add build properties file
This makes downstream build easier to configure web-client information.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #548

Easy build-time overriding of distribution URLs for bug trackers, mailing list, product name, etc.

### CODE REVIEW

**Review by tthvo — APPROVED** [review]
Looks good! Worked for me :D I just file an issue and reference it here.

**Review by ebaron — COMMENTED** [review]
Looks good! How easy would it be to customize the version link as well? For downstream builds I patch out the link since the commit hash does not refer to an upstream commit. Is it possible to make it a URL parameter in the JSON file and if empty/unset the `href` is omitted?

**Comment by andrewazores** [comment]
> Looks good! How easy would it be to customize the version link as well? For downstream builds I patch out the link since the commit hash does not refer to an upstream commit. Is it possible to make it a URL parameter in the JSON file and if empty/unset the `href` is omitted?

If I understood correctly, the last commit makes this easy now. Just patch the `build.json` and set `"commitHashUrl": ""` and the text component will simply render the version string reported by the backend, with no linking to the upstream repo.

**Review by ebaron — APPROVED** [review]
Thanks for doing that as well, that's exactly what I had in mind.

**Pull request merged**
