### PR TITLE
Custom targets

### PR DESCRIPTION
**Pull request by andrewazores**
#212

### CODE REVIEW

**Comment by Alexjsenn** [comment]
Hey, so I was testing this out and I created a fake target similar to what you had suggested when testing out the api implementation, but when I select this new target and then go to the recordings tab, it crashes. I got the same result in both chrome and firefox. Do you get the same behaviour or is something wrong on my end?

**Comment by andrewazores** [comment]
What happens when it "crashes" - is this a frontend error message or an actual backend Cryostat API error?

Did the target you defined point to a target that actually existed/was reachable?

**Comment by Alexjsenn** [comment]
No, it did't point to anything that existed. I ran it in smoketest and I added: service:jmx:rmi:///jndi/rmi://cryostat:9099/jmxrmi
The browser tab just stops responding.

**Comment by andrewazores** [comment]
Interesting, thanks for that note - I'll take a look at it. Sounds like I made some kind of React mistake.

**Comment by andrewazores** [comment]
> No, it did't point to anything that existed. I ran it in smoketest and I added: service:jmx:rmi:///jndi/rmi://cryostat:9099/jmxrmi
> The browser tab just stops responding.

Actually, I see this behaviour on `main`, not just on this PR's branch. Do you see that too? I'll investigate the root cause further and open a separate PR.

**Comment by andrewazores** [comment]
After a git bisect, the first bad revision appears to be `441b63dbbe695a5ff36fe08c3a196d9808078343` - that's #214 , which touched the `ActiveRecordingList`, so that looks plausible.

@Josh-Matsuoka if you have some free cycles, could you take another look at that? If not then I'll take it on.

**Comment by andrewazores** [comment]
@Alexjsenn for the purposes of testing the functionality in this PR, I'm going to rebase it onto `main` as of a couple of commits back and force-push it here.

Try adding `service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi` as a custom target definition as well - this should instruct the Cryostat JVM to connect back to itself, so you can easily test out a target definition that does actually point to something.

**Comment by Alexjsenn** [comment]
> @Alexjsenn for the purposes of testing the functionality in this PR, I'm going to rebase it onto `main` as of a couple of commits back and force-push it here.
> 
> Try adding `service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi` as a custom target definition as well - this should instruct the Cryostat JVM to connect back to itself, so you can easily test out a target definition that does actually point to something.

Ok, it works perfectly now!

**Review by Alexjsenn — APPROVED** [review]

**Comment by Josh-Matsuoka** [comment]
@andrewazores hey, I'll take a look at that bug this week, sorry about that.

**Comment by andrewazores** [comment]
> @andrewazores hey, I'll take a look at that bug this week, sorry about that.

No worries, I should have caught it in review as well.

**Pull request merged**
