### PR TITLE
chore(eslint): apply eslint fixes and remove unused codes

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] Signed the last commit: `git commit --amend --signoff`
_______________________________________________

Related to #941 

### Chores
- Remove unused codes.
- Apply eslint fixes.
- Use `FC` alias for `FunctionComponent` (perhaps code base can be a little bit smaller?).

### Fixes

- Fixed infinite effect loop error by removing effect that open the problem section.
  - **How to reproduce**: launch cryostat only with `run.sh`, observe the problem notification, and the browser console will show error with title `Warning: Maximum update depth exceeded. `
  -  Fix by remove buggy effect and open the problem by default. This fix also allow users to close the problem notification section if needed (previously not possible).

## Motivation for the change:

Regular "house-keeping" for codebase.

### CODE REVIEW

**Comment by tthvo** [comment]
Seems like if the user chooses minimal deployment, the infinite effect loop error will cause the web-client to be significantly slow. Should be backport this?

**Comment by andrewazores** [comment]
> How to reproduce: launch cryostat only with run.sh, observe the problem notification, and the browser console will show error with title Warning: Maximum update depth exceeded. 

I wasn't able to reproduce this (backend commit: `332fcbee8b7469935b88f1934dae917f24a3d5c5`), I just see a warning notification and no error in the console.

**Comment by tthvo** [comment]
> I wasn't able to reproduce this (backend commit: 332fcbee8b7469935b88f1934dae917f24a3d5c5), I just see a warning notification and no error in the console.

Opps I left out an important step: you need to launch a dev server for front-end to see react warning. Production asset won't show it.

**Comment by andrewazores** [comment]
I tried:

```bash
$ CRYOSTAT_DISABLE_SSL=true CRYOSTAT_CORS_ORIGIN=http://localhost:9000 sh run.sh
```

in one terminal, and:

```bash
$ yarn start:dev
```

in another. I get this:

Screenshot_2023-06-02_17-59-57

I have no issues with opening the notification drawer and no error in the console...

**Comment by tthvo** [comment]
Okayy! Then this PR fixed it right?

**Comment by andrewazores** [comment]
With this PR branch checked out, repeating the steps above seems to fix it - I can open and close the notification drawer as well as the Problems section, and there is no console error.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
