### PR TITLE
fix(images): add favicon and brand image

### LINKED ISSUE #279: Missing favicon and about modal logo

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #279

Depends on #281

image

### CODE REVIEW

**Comment by jiekang** [comment]
I think for the black background, we can use a version that's white. I can generate one for you. Thoughts?

**Comment by jiekang** [comment]
Also I can generate an Icon version that you can add; it's a bit weird to see the full Cryostat logo along with the Cryostat text immediately under it...

**Comment by jiekang** [comment]
Oh and I need to make the background for the favicon transparent. Oops

**Comment by andrewazores** [comment]
Sure, that all sounds good.

**Comment by hareetd** [comment]
I like the logo, looks good :)

Also, I understand what the other changed files do but what is `webpack.common.js` responsible for? How does it fit in with the rest?

**Comment by andrewazores** [comment]
So, the overall build process for a React application typically has a few steps. `tsc` is the TypeScript compiler, which compiles TypeScript down to plain JavaScript that a browser can execute. This gets invoked by Webpack, which also does various other things for us, and is typically called a "bundler". Webpack's main job is to gather up all the pieces of the app - `.js`, `.html`, `.css`, images/fonts/etc., and assemble it into some kind of usable end format. In our usual build process that's the `dist` directory, which ends up containing `index.html` (which is the same `index.html` from `src`, but with the `favicon` link generated and placed into it), various `app.bundle.js` files containing the TypeScript side of our React components and our various JS dependencies, and again fonts/images/etc.

`webpack.common.js` is the main configuration for Webpack. `webpack.prod.js` contains additional settings/overrides used for production builds, which is what you get when you do `yarn build` (and what goes into a finished Cryostat image when you do `mvn package`). `webpack.dev.js` contains settings/overrides for the webpack-dev-server (`yarn start:dev`).

**Comment by hareetd** [comment]
Makes sense, thank you.

**Comment by andrewazores** [comment]
Here's the latest update:

image

**Comment by jiekang** [comment]
Hm... Okay so atm there's Cryostat icon on top of the text, but the vertical spacing between them is quite large. I think it would be best to replace the both of them with just a Cryostat logo image instead.

**Comment by andrewazores** [comment]
FWIW that's what the Patternfly example component looks like: https://www.patternfly.org/v4/components/about-modal

I can make it look like this easily enough however:

image

**Comment by jiekang** [comment]
Oh... well damn. The vertical space is so off though :|

**Comment by jiekang** [comment]
@andrewazores any chance you could share another screenshot of what it looks like now?

**Comment by andrewazores** [comment]
image

image

**Review by jiekang — DISMISSED** [review]
One nit:

Is `src/app/assets/cryostat-3-icon-white-500px.png` file still needed? Rest LGTM.

**Comment by andrewazores** [comment]
> One nit:
> 
> Is `src/app/assets/cryostat-3-icon-white-500px.png` file still needed? Rest LGTM.

It was unused, so I've removed it and rebased. There was just one small conflict with some imports.

**Review by jiekang — APPROVED** [review]

**Pull request merged**
