### PR TITLE
chore(eslint): add eslint-webpack-plugin

### PR DESCRIPTION
**Pull request by maxcao13**
Signed-off-by: Max Cao <macao@redhat.com>

# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] Signed the last commit: `git commit --amend --signoff`
_______________________________________________

Fixes: #841 

## Description of the change:
This change allows eslint errors and warnings to be shown during the webpack development compilation build status.
This only works during a development build using `yarn start:dev`

## Motivation for the change:
See #841 

## How to manually test:
1. checkout pr and `yarn install`
2. Run cryostat with this pr -web client with `yarn start:dev`
3. Go to a file like AboutAgentCard.tsx in `src/app/Agent/AboutAgentCard.tsx` 
4. Change the import order of the 2 imports
5. Notice the webpack eslint warning

### CODE REVIEW

**Review by tthvo — COMMENTED** [review]
Looks good to me! Just one concern is that launching dev server seems to take longer for eslint-plugin to register. Been seeing a increase to about 15-20 seconds.

```bash

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/, http://127.0.0.1:9000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/thvo/workspace/cryostat-web/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /
70% sealing finish module graph ESLintWebpackPlugin_1
```

**Comment by maxcao13** [comment]
Seems like on the [eslint-web](https://github.com/webpack-contrib/eslint-webpack-plugin/) github page, a lot of people are dealing with performance issues. I'm not sure if there is anyway around that without sacrificing something else. For example, I tried using the option `lintDirtyModulesOnly` and what that does is that it doesn't run an eslint check on startup, but only after the webpack build finishes and it detects any changes on that changed file.

We can either keep the extra 20 second compilation time, which sort of makes sense for the development build since the main cryostat image smoketest takes a bit longer with the new `mvn:evaluate` changes vs the old `xpath`.

Or we can use this `lintDirtyModulesOnly` option, and just remember that any changed files before running the dev build will be unlinted and just be cautious.

I've also only noticed this now, but it seems one rule is taking all the compute time for eslint checks. Maybe that is the issue...
```bash
$ TIMING=1 yarn eslint:check

Rule                                 | Time (ms) | Relative
:------------------------------------|----------:|--------:
import/namespace                     | 10338.520 |    88.6%
unused-imports/no-unused-imports     |   167.563 |     1.4%
react/no-direct-mutation-state       |   156.317 |     1.3%
import/order                         |   142.964 |     1.2%
react/display-name                   |   137.746 |     1.2%
import/no-duplicates                 |    85.290 |     0.7%
react-hooks/exhaustive-deps          |    72.994 |     0.6%
react/require-render-return          |    61.779 |     0.5%
no-unexpected-multiline              |    30.712 |     0.3%
@typescript-eslint/no-empty-function |    29.946 |     0.3%
```

**Comment by andrewazores** [comment]
> since the main cryostat image smoketest takes a bit longer with the new mvn:evaluate changes vs the old xpath.

Yea, this is unfortunate, but it's probably overall nicer that the script no longer requires `xpath` to be installed. Maybe the script should check if `xpath` is available and use it if so, falling back to `mvn:evaluate` if not.

I've been using `mvnd` for the most part and it helps make `mvn:evaluate` faster since it doesn't need a JVM to start up each time just to read the `pom.xml`, it reuses a running JVM to read the file:

https://github.com/apache/maven-mvnd

And in `$HOME/bin/mvn` I have a script like this:

```bash

```#!/bin/sh

# /usr/bin/mvn $@
mvnd -Dmvnd.rawStreams $@
rc=$?
if [ -z "$MVN_BUILD_TITLE" ]; then
    MVN_BUILD_TITLE="Maven"
fi
notify-send "$MVN_BUILD_TITLE" "Build $([ $rc == 0   ] && echo Succeeded || echo Failed)"
exit $rc

**Review by tthvo — APPROVED** [review]
Looks good to me! First build is slow but later builds are pretty fast :D

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
