### PR TITLE
build(ci): submodule should sign commits

### PR DESCRIPTION
**Pull request by aali309**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #916 

## Description of the change:
This change will sign all commits on `git submodule update`

## Motivation for the change:
All commits should be verified.

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...*
2. *...*

### CODE REVIEW

**Review by tthvo — COMMENTED** [review]
I think the environment currently does not have the gpg/ssh key to sign the commits. We need to import them.

This could be useful: https://github.com/crazy-max/ghaction-import-gpg

**Review by andrewazores — COMMENTED** [review]
Looks like it makes sense. Just rebase it please, then @ebaron or I will have to generate that key and set up a GitHub Secret for it.

**Comment by tthvo** [comment]
Also @aali309 would u want to do the same for helm chart? https://github.com/cryostatio/cryostat-helm/blob/main/.github/workflows/submodule.yml

**Comment by andrewazores** [comment]
I should finally be able to generate the key and set it as a secret now. Please rebase one more time :-)

**Review by andrewazores — APPROVED** [review]

**Comment by andrewazores** [comment]
Looks good:

image

**Comment by tthvo** [comment]
@andrewazores @aali309 How about this?

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-bots

Removing these lines, in theory, would allow the commits to be verified?

https://github.com/cryostatio/cryostat-web/blob/b1c536817346a3bec50f5a91e12995bee474a5fa/.github/workflows/submodule.yaml#L46-L47

**Comment by andrewazores** [comment]
Nice find. Let's try it out. I don't think we depend on the bot's name for any other CI steps or anything like that.

**Pull request merged**
