### PR TITLE
feat(login): display notification on bad credentials

### LINKED ISSUE #237: Authentication Failure should produce a notification
> I attempted to log in with a fake token to see what would happen and there was no visual indicator in the UI, but there was a 401 Unauthorized in the log. I'm not sure if this differs at all from the current behaviour.

I believe that's normal, although now that you mention it, there probably should be some indication that the request was made and rejected.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/599#issuecomment-895526430_

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #237

### CODE REVIEW

**Comment by jan-law** [comment]
Is there a way to test this PR without running CRC? I don't have enough RAM on my laptop to run CRC :/

**Comment by andrewazores** [comment]
Sure, just run it with the BasicAuthManager setup again. The notification appears for either form of credentials (Basic or Bearer token).

**Review by jan-law — COMMENTED** [review]
UI looks good! The code also makes sense.

For my own learning, would the 2.0 release also 'forget' your credentials after you refresh the browser tab? After a user logs into Cryostat, how would they log out if they wanted to switch users?

**Comment by andrewazores** [comment]
Correct, 2.0 UI will still forget your credentials. If you need to switch users you can open a new tab or refresh the current one.

The UI could save the user's credentials into a cookie or localStorage and have a user menu with logout button, but this just hasn't been implemented. PRs accepted, if you're interested, but if it's going into 2.0 the merge window has become very short :-)

**Review by jan-law — APPROVED** [review]
I'll make a note to look into saving credentials into cookies or localStorage after the release. For now, PR looks good.

**Pull request merged**
