### PR TITLE
feat(archive): display file size for archived recordings

### LINKED ISSUE #491: [Task] The recordings actions drop-down is cut off in the Archives view
Related #431

https://user-images.githubusercontent.com/41028544/182445533-b606c021-a4f7-4e34-9586-8ff0b13ba48f.mov

### LINKED ISSUE #516: [Task] Add recording size fields to archived recordings tables
https://github.com/cryostatio/cryostat/issues/964

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #516
Fixes #491
Related to #532

**Features**
- Added recording size column for archived table.
- All recording tables are now scrollable (previously only All-archives view). Default height size is `500px`.

**Fixes**:
- Appended action menus to higher element - `document.body` in DOM tree (avoiding cut-off). Had to create manual dropdown as patternfly `ActionColumn` is not configurable for this issue. 
- Snapshot tests for recording tables are dropped as rendering requires DOM, and replaced with tests that checks if elements are visible as expected with `js-dom`.
- `ActiveRecording` and `ArchivedRecording` are now different types (i.e. no inheritance) with `Recording` as their representing Union type.

### CODE REVIEW

**Comment by tthvo** [comment]
Currently, this is our new archive table look. I placed the total size on the bottom right and size it up. Probably, there is a better place and style for it.

Total size changed dynamically with filters (only reflects whatever is visible).

Screenshot from 2022-10-05 22-00-18

**Review by andrewazores — DISMISSED** [review]

**Comment by tthvo** [comment]
Sorry, just rebasing and refactoring the height size to `.css` with value set to `512px` instead (i.e. span more free space if view-port is large).

**Comment by lkonno** [comment]
In my opinion, the `Labels` field should come first. The `Total size` could be right below the `size` field. I tried to edit the image with my suggestion. What do you think?

suggestion

**Review by maxcao13 — APPROVED** [review]
Makes sense and looks good to me!

**Review by lkonno — APPROVED** [review]
It looks good!

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
