### PR TITLE
build(webpack): cache production builds

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] Signed the last commit: `git commit --amend --signoff`
_______________________________________________

Fixes: #790 

## Description of the change:

Enable production build cache.

## Motivation for the change:

See #790 

## How to manually test:

Build with:

```bash
yarn build:notests
```

Then, rebuild without changing any source files and observe the time taken.

### CODE REVIEW

**Comment by tthvo** [comment]
Hmm...I wonder if its due to ci changs that build (16.x) step is stuck...

**Review by maxcao13 — APPROVED** [review]
First build took 11 seconds, second build took 2 seconds. LGTM!

**Comment by tthvo** [comment]
Ahh seemed to fix ci if remove cache action...maybe ci should be running fresh build anyway :D

**Comment by andrewazores** [comment]
I think running fresh builds always in CI makes sense.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
