### PR TITLE
feat(topology): add target.Agent topology filter 

### PR DESCRIPTION
**Pull request by mwangggg**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #1325

### CODE REVIEW

**Review by tthvo — COMMENTED** [review]
Just a thought here:

Since the available filter categories are actually based on what is being displayed in the Entity Detail page:

image

Maybe, we can figure a way/design (e.g. another description list item) to show if a target is configured with Agent or not. Then, we base on that to display the filters. What do you think?

**Comment by andrewazores** [comment]
The `target.agent` property is basically just shorthand for `target.connectUrl.startsWith('http')`, so I'm a little conflicted on whether it deserves its own separate list item. But, if we don't list it there, then users may not realize it's available to reference in their expressions.

**Comment by tthvo** [comment]
> The `target.agent` property is basically just shorthand for `target.connectUrl.startsWith('http')`, so I'm a little conflicted on whether it deserves its own separate list item. But, if we don't list it there, then users may not realize it's available to reference in their expressions.

Ah right, how about just an Info icon that shows next to the `connectUrl` of an Agent-based taget? This is compact and also gives an example expression. A small diff here (using Patternfly 5, PF4 might look a bit different): https://gist.github.com/tthvo/2c05f789cccbb759745bd3ec4ddee806

image

**Comment by tthvo** [comment]
Quick question tho @andrewazores @mwangggg . Should this target `pf5` branch? I am hoping the upgrade will finish in the next 1-2 weeks or so. Just that there might be a huge conflicts to resolve after merge :D

**Comment by andrewazores** [comment]
I'm fine with that.

I'll go ahead and merge this into `main` for now so that it doesn't just sit idle doing nothing, then either rebase `pf5` onto `main` or merge `main` into `pf5`, and feel free to update/alter the new desig in another PR targeting the `pf5` branch.

**Pull request merged**
