### PR TITLE
feat(credentials): nested match expressions table

### LINKED ISSUE #466: [Task] Implement nested table for `matchExpression` Credentials
Parent: https://github.com/cryostatio/cryostat-web/issues/465

> https://github.com/cryostatio/cryostat/pull/1000 adds a new API call that should be used for a revamped JMX Credentials view within the Security section. This structure seems well-suited to a table where each row corresponds to a matchExpression, and the row can be expanded to reveal a nested table of targets.
>
> The matchExpression rows should be selectable, including with a header checkbox to select all, so that the row can be deleted. This deletion operation is partially supported in https://github.com/cryostatio/cryostat/pull/1000 - the internal call exists, but there is no v2.2 API handler for the deletion yet.

### PR DESCRIPTION
**Pull request by hareetd**
Fixes #466 

Includes some minor fixes to the nested table implementation in the `AllTargetsArchvedRecordingsTable`. 

image

### CODE REVIEW

**Comment by andrewazores** [comment]
Just looks like the test snapshot needs updating.

**Comment by hareetd** [comment]
Ah, I forgot to update/add tests, thanks.

**Comment by andrewazores** [comment]
Ah, I see this is still a draft. Carry on :-)

**Comment by andrewazores** [comment]
I notice that after first adding a new credential from directly within the Security view, the new row gets added to the table but the count badge is missing. If I navigate away to some other view and then back to Security then the badge appears with the expected number.

**Comment by andrewazores** [comment]
Also the badge doesn't seem to live-update with target discovery notifications while I'm on the Security view - at least not "LOST" notifications, which are all I tried.

**Comment by hareetd** [comment]
Sounds good, thanks for the feedback.

**Comment by hareetd** [comment]
I realized while writing tests that the notification handling for deleted credentials in `StoreJmxCredentials` was broken. Specifically, the notifications would come through but not all of the corresponding credentials would be removed from the table. My first thought was that the rendering was having issues due to improper state handling. 

Considering I have a lot of state objects (`credentials`, `expandedCredentials`, `checkedCredentials`, `isHeaderChecked`, and `counts`) that are related to each other and as a result, are frequently updated at the same time, I decided to convert their handling from `useState` to  [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer). Unfortunately, this didn't fix the original problem.

I then realized since the synchronous notification handling for deleted credentials is more involved than usual (relative to other components) some of the asynchronous notifications from the `Subscription` were being missed and going unprocessed. So I decided to use  `concatMap` in conjunction with `of` to ensure each notification would be processed before proceeding to the next:

```
 React.useEffect(() => {
    addSubscription(
      context.notificationChannel.messages(NotificationCategory.CredentialsDeleted)
      .pipe(concatMap(v => of(dispatch({ type: Actions.HANDLE_CREDENTIALS_DELETED_NOTIFICATION, payload: { credential: v.message }}))))
      .subscribe(() => {} /* do nothing - dispatch will have already handled updating state */)
    );
  }, [addSubscription, context, context.notificationChannel]);
```
I wonder how many of our other components also have this same issue but we haven't realized since the type of notifications they handle don't typically get spammed when testing?

**Comment by hareetd** [comment]
Taking a look at the [`ArchivedRecordingsTable`](https://github.com/cryostatio/cryostat-web/blob/756d9ea7e42ae4949ca319715eba098e52754cd4/src/app/Recordings/ArchivedRecordingsTable.tsx#L200), it looks like the notification handling for deleted recordings is fairly involved but there is no such issue present there. 

I wonder if my issue is due to the nature of setting up a nested table using `useEffects` with dependencies (credentials, counts, etc.) that are frequently updated at the same time (at least, at a more frequent rate than our more typical components) or whether my design approach is incorrect?

**Comment by andrewazores** [comment]
I'm not sure - this is a tough thing to track down. `useReducer` was a good idea to try to tackle the problem.

It might be as simple as a state hook not updating, though. IIRC the elements within the dependencies array are only compared by reference, not by value, and not by any deep comparison. So for example, if you have a piece of state that is actually an array or a Map etc. and you mutate that object, the reference remains the same and the hook will not update.

But your hunch that it could be timing related also seems completely possible.

**Comment by andrewazores** [comment]
Last commit looks like it solved it :-)

**Comment by hareetd** [comment]
Yeah, looks like it was a timing issue. I've modified the `AllTargetsArchivedRecordingsTable` to ensure synchronous notification  target-related notification handling as well, just in case.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
