### PR TITLE
fix(graphql): adjust GraphQL queries and models for updated server schema

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Includes:
- [x] #1219
- [x] #1220
- [x] #1221
- [x] #1224
- [x] #1227

Depends on https://github.com/cryostatio/cryostat3/pull/294

## Description of the change:
*This change adds allows a match expression example to be copied to the clipboard...*

## Motivation for the change:
*This change is helpful because users may want to copy the example for easier use...*

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...*
2. *...*

### CODE REVIEW

**Comment by andrewazores** [comment]
@aali309 could you take a look at updating the unit tests related to the archived recordings views from your recent PR?

https://github.com/cryostatio/cryostat-web/actions/runs/8670862635/job/23779369922

**Comment by andrewazores** [comment]
Hmm nevermind, looks like it may have been just a merge issue.

**Comment by andrewazores** [comment]
Sorry, there was a merge issue, somehow it didn't merge properly from the PR and my first manual attempt was wrong. I think I have corrected it now and there are indeed unit test failures.

**Comment by andrewazores** [comment]
Also, "View in Grafana" on the Uploaded Archives view isn't working. I will help look into that one however, since it may be a similar issue to https://github.com/cryostatio/cryostat3/pull/324 on the server side.

**Comment by aali309** [comment]
Ok I will look into it also and update you.

**Pull request merged**
