### PR TITLE
fix(target): update target selection cache

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] Signed the last commit: `git commit --amend --signoff`
_______________________________________________

Partial fixes: #805 
Related to: https://github.com/cryostatio/cryostat/pull/1327 (WS notifications should be sent).

## Description of the change:

Update target cache to save only connectUrl and should update currently selected target with new details.

## Motivation for the change:

See #805

## How to manually test:
1. `Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...`
2.  Choose any target with credentials. Either enter credentials using Auth modal or add in Security Panel.
3. Expand the target details. See the jvmId being updated.

### CODE REVIEW

**Comment by andrewazores** [comment]
I think it might be better to just ensure that the Targets model is fully synchronized with the backend by using our usual pattern of WS notifications.

On the backend, when new Credentials are added, the DiscoveryStorage observes this event and checks which targets it applies to. It maintains a collection of observed targets that it previously was unable to connect to, so it tries to connect to each of those again using the new credentials, and tries to populate the `jvmId` field.

*If that succeeds*, then a WebSocket notification should be emitted with the updated targets' state. The frontend can figure out how to merge that updated state into its current model, or it can simply drop its model and query to replace it entirely.

This way all of the logic to do with how things update (or are created and deleted), and the relationships and dependencies between things, is all implemented wholly on the backend. The frontend should stay as simple and presentational as possible.

There are a few reasons and benefits to doing things that way. First, it keeps things easier to maintain, since the logic is only located in one place instead of being implemented twice, where both implementations need to be kept in sync with each other. Second, it means that it's easier to reason about what the data model displayed by the frontend is since it is always just a prettified rendered view of what the API responses would return for an equivalent `curl` request.

On that second note, I think there is actually a nefarious bug in this PR's implementation. Since the target refresh query is triggered by the auth modal submission, the frontend instance's Target data model will only be refreshed and synchronized with the backend when *this* frontend instance is the one that added the new credentials. If there are multiple frontend instances, or if there is a `curl` API request etc. that adds the credentials, then the data model remains desynchronized until some other event occurs that triggers a query and full resync.

**Comment by tthvo** [comment]
Ahh that would be better to send notification from backend then. I will remove the 'tap' to query targets but we might need to fix local storage cache. Will check backend to add fixes. Thanks for explaining :D

**Comment by andrewazores** [comment]
Should the cached selection actually be the `jvmId` perhaps?

**Comment by tthvo** [comment]
> Should the cached selection actually be the jvmId perhaps?

Was just concerned that some has null jvmId (like this scenario) so selecting any of them will take the first matched. So connectUrl might be a better option?

**Comment by andrewazores** [comment]
Ah, that's true.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
