### PR TITLE
chore(pf5): upgrade Settings view to Patternfly 5

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #1303 

## Description of the change:

- Upgraded Settings View to Patternfly 5.
- Dark mode should be functional now.

## Minor changes

| Changes | Description | Screenshot |
|--------------|-------------------|------------------|
| Descriptions for Feature level selection | Such explanations can be useful for users that are not familiar with these (i.e. beta) notions | image |
| Full word for unit of websocket retry config | This is consistent other configurations, for example, Auto Refresh | image |
| Configurations are formatted to be human-friendly | This ensures consistency with Recording View and elsewhere | image |

## Major changes

| Changes | Description | Screenshot |
|--------------|-------------------|------------------|
| Dedicated action list for saving configuration form | This ensures consistency of Form pattern across the UI | image |
| New theme toggle on masthead | Switching theme should be quick & seamless. This design is pretty common. For example, [Podman docs](https://podman.io/docs) andn [Patternfly docs](https://www.patternfly.org/). For us, we follow the Patternfly way | image |

### CODE REVIEW

**Comment by andrewazores** [comment]
Awesome!

image

I tried typing `English (Canada)` in the search field here, but it blows up the page :-) As soon as I hit `(` there was an uncaught error about "unterminated parenthetical". Same thing if I type `(` in the timezone search.

image

Maybe this should be `Millisecond*s*`?

**Comment by tthvo** [comment]
> image
> 
> I tried typing `English (Canada)` in the search field here, but it blows up the page :-) As soon as I hit `(` there was an uncaught error about "unterminated parenthetical". Same thing if I type `(` in the timezone search.

Uhhh opps, my bad ^^ Looks like we didn't escape the search text. It should be fixed :D

> image
> 
> Maybe this should be `Millisecond*s*`?

Yep just did^^

**Comment by tthvo** [comment]
In the latest commit, I added some css fixes for elements (i.e. those that were upgraded to PF5) to be compatible with dark theme. I think we fix the rest while upgrading other remaining views :D

**Review by andrewazores — APPROVED** [review]
LGTM, @tthvo please take a quick look over the localizations I extracted in the last handful of commits.

**Comment by tthvo** [comment]
> LGTM, @tthvo please take a quick look over the localizations I extracted in the last handful of commits.

Oh nicee! Looks good to me! Thanks for handling that :D

**Pull request merged**
